################################
# PixieHub by the PixieWorkshop#
################################

#-- Options --#
# This feature will only work on players with the 'pixie.joinfly' permission #
UseJoinFly: true
UseDoubleJump: true
UseCustomJoinMessage: true

MessageOnHub: true
TeleportOnVoid: true
TeleportOnJoin: true

#-- Disabled Functions --#
DisableFunctions:
    item-drop: true # override permission pixie.override.id #
    item-pickup: true # override permission pixie.override.ipu #
    player-hunger: true # this disabled a player from lossing hunger #
    player-health: true # this disables a player from taking damage #
    join-message: false
    quit-message: false

# all of these commands teleport the player to the hub location. if you change one of these settings you will need to restart the server, reloading the config will not apply these changes #
CommandOptions:
    hub: true
    spawn: true
    stuck: true
    lobby: false
    l: false
    custom-help-command:
        use: true
        lines:
        - '&7----------MyHub----------'
        - '&cExample. how cool!'
        - '&7-------------------------'

#-- SilentJoin --#
# Players with the permission 'pixie.silentjoin' will not broadcast a join message upon joining the server #
UseSilentJoin: true

#-- Chat --#
# Player with the permission 'pixie.chat.bypass' will bypass the chat cooldown #
UseChatFilter: true
UseChatCooldown: true
CooldownTimer: 3 # In seconds #

#-- Holograms --#
Holograms:
    spacing: 0.3 # default, recommended not to go any lower that this #

#-- JumpPads --#
JumpPads:
# allow jump sound on jumppad use. #
    jump-sound: true
# allow particle effect on jumppad use. #
    jump-effect: true
# if player-heath is true, this does not matter. #
    disable-fall-damage: true
# automatically activated when a player walks on this block #
    block: SLIME_BLOCK

#-- Server Settings --#
ServerSettings:
    use: true # use serversettings #
    max-players: 50

    motd: '&d&lMy server uses PixieHub!                       &c ➥ [1.8-1.17]'
    maintenance-motd: '&cThis server is down for maintenance!'
    maintenance-kick: '&cThe server has entered maintenance mode.'
    maintenance-disconnect: '&cYou can not join the server while it is in maintenance mode.'

# Do Not Change -_- #
config-version: 2.0